import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import Card from "../components/card.component";
import NavBar from "../components/nav-bar";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Image App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="main">
                <div className="card-layout">

                  <Card/>
                  <Card/>
                  <Card/>
                  <Card/>
                  <Card/>
                  <Card/>
                  <Card/>
                </div>
                <NavBar/>
            </main>
        </div>
    );
}
